### ISSUE TITLE
implementation for Ionic 2

### ISSUE THREAD

**Issue by aarshad786** [AzureAD/azure-activedirectory-library-for-cordova#145] opened 2017-04-21 15:44 UTC
### Issue Description
adding the plugin using Ionic plugin add cordova-plugin-ms-adal
declare var Microsoft: any; 

var authContext = new Microsoft.ADAL.AuthenticationContext(this.authority);
this.authContext.acquireTokenSilentAsync(this.resourceUrl, this.appId).then(
authCompleteCallback, function(){
this.authContext.acquireTokenAsync(this.resourceUrl, this.appId, this.redirectURL).then(authCompleteCallback, function(){
console.log("Unable to authenticate")
});
});

This code passes compilation and runs on device, however prompt for login is not shown.

NOTE: this is part of method which is called on platform.ready().then()

### Repro Environment Details
1. Installed plugin version:  0.9.0
2. Target Platform: Android iOS
3. Test device and OS version: Android => 5.1.1, 6.0, 7.0 , iOS => 10.2

**Comment by matrosov-nikita** [comment] 2017-04-23 14:19
Hi @aarshad786, I've tried to reproduce this bug with sample Ionic2 app (tabs) w/o success.
Could you please verify that your cache does not contain any items before acquiring token by following [this guide](https://github.com/AzureAD/azure-activedirectory-library-for-cordova#tokencache). Also, check if there are errors in the console using chrome dev tools.

**Comment by aarshad786** [comment] 2017-04-24 11:21
@matrosov-nikita , Can you share the code via repository? 
I have used
authContext.tokenCache.clear(); 
the problem still persists.

TIA

**Comment by matrosov-nikita** [comment] 2017-04-24 19:39
@aarshad786, sure, I created a [repository](https://github.com/matrosov-nikita/ionic-adal-proj) for you  with sample Ionic2 app which contains logic for token acquisition. 

Run the following commands:
`npm install`
`ionic platform add android`
`ionic run android`

Let me know if you have any questions.

**Comment by aarshad786** [comment] 2017-04-24 20:21
@matrosov-nikita , thanks for your help on this.
I am still facing the same issue,
console.log showed Unable to acquire token.
I tweaked it more to 
function (error) {
              console.log("Unable to acquire token. Error:"+error);
            });
and found out that it was giving error code -11.

Code:-11 primary error: 3 certificate: Issued to: CN=*.login.windows.net;


Thanks once again for your help

**Comment by matrosov-nikita** [comment] 2017-04-25 08:36
@aarshad786, thanks for verification. It looks like certificate validation issue. According this [arcticle](https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue) from native ADAL, you should upgrade `Android System Wevbiew`.
Also, this issue has already been discussed [here](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/111).

**Comment by matrosov-nikita** [comment] 2017-04-28 14:00
@aarshad786, just a friendly ping.

**Comment by aarshad786** [comment] 2017-04-28 15:51
@matrosov-nikita, (Y).. thanks man for all the help.. updating chrome and System Webview worked!!!

**Comment by matrosov-nikita** [comment] 2017-04-28 17:33
@vladimir-kotikov, can we close this issue?

**Closed** 2017-04-28 19:19 UTC
