### ISSUE TITLE
Windows Phone 8.1 build fails to deploy from Visual Studio.

### ISSUE THREAD

**Issue by SPDoctor** [AzureAD/azure-activedirectory-library-for-cordova#45] opened 2016-02-24 18:49 UTC
When using version 0.6.2 of the plug-in I am seeing an error "Error : DEP6810 : MdilXapCompile.exe failed with error code 2001" when I try to deploy to Windows Phone 8.1. All other platforms seem to deploy correctly (including Windows 10 phone). I am using VS2015 with the latest update of the tools for Apache Cordova and the error is in the main project when I try to deploy to phone.

If I drill down to the generated VS solution under platforms/windows and deploy to the device from that solution (targeting Any CPU) it deploys and works correctly on the device.

If I use version 0.6.0 of the plug-in (the version retrieved by the VS tooling as a "Core" plugin) the project deploys to the device but the function acquireTokenAsync never invokes its promises and so it doesn't work, which may be expected behaviour with this older version.

**Comment by sgrebnov** [comment] 2016-02-25 11:29
@SPDoctor, could you please try a clean build? I've tried both VS and command line and it works for me.

```
>Build started 2/25/2016 2:27:52 PM.
1>     1>
1>InstallMDA:
1>         Your environment has been set up for using Node.js 0.12.7 (ia32) and npm.
1>         ------ Ensuring correct global installation of package from source package directory: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ApacheCordovaTools\packages\vs-tac
1>         ------ Name from source package.json: vs-tac
1>         ------ Version from source package.json: 1.0.34
1>         ------ Package already installed globally at correct version.
1>       BuildMDA:
1>         ------ Cordova tools 5.4.1 already installed.
1>         ------ Build Settings:
1>         ------ Build Settings:
1>         ------    platformConfigurationBldDir: c:\temp\BlankCordovaApp2\bld\Windows Phone (Universal)\Debug
1>         ------    platformConfigurationBinDir: c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug
1>         ------    buildCommand: build
1>         ------    platform: Windows Phone (Universal)
1>         ------    cordovaPlatform: windows
1>         ------    configuration: Debug
1>         ------    cordovaConfiguration: Debug
1>         ------    projectName: BlankCordovaApp2
1>         ------    projectSourceDir: c:\temp\BlankCordovaApp2
1>         ------    npmInstallDir: C:\Users\Sergei\AppData\Roaming\npm
1>         ------    buildTarget: AppHostLocalDebugger
1>         ------    language: en-US
1>         ------ Adding platform: windows
1>         Executing "before_platform_add"  hook for all plugins.
1>         No version supplied. Retrieving version from config.xml...
1>         Adding windows project...
1>         Failed to require PlatformApi instance for platform "windows". Using polyfill instead.
1>         Running command: cmd "/s /c "C:\Users\Sergei\.cordova\lib\npm_cache\cordova-windows\4.1.0\package\bin\create.bat c:\temp\BlankCordovaApp2\platforms\windows io.cordova.myapp2231fa BlankCordovaApp2""
1>         Creating Cordova Windows Project:
1>         	App Name  : BlankCordovaApp2
1>         	Namespace : io.cordova.myapp2231fa
1>         	Path      : c:\temp\BlankCordovaApp2\platforms\windows
1>         Copying template to c:\temp\BlankCordovaApp2\platforms\windows
1>         Command finished with error code 0: cmd /s /c "C:\Users\Sergei\.cordova\lib\npm_cache\cordova-windows\4.1.0\package\bin\create.bat c:\temp\BlankCordovaApp2\platforms\windows io.cordova.myapp2231fa BlankCordovaApp2"
1>         Executing "before_build"  hook for all plugins.
1>         Executing "before_prepare"  hook for all plugins.
1>         Searching PlatformJson files for differences between project vs. platform installed plugins
1>         No differences found between project and windows platform. Continuing...
1>         Executing "pre_package"  hook for all plugins.
1>         Resolving module name for shelljs => shelljs
1>         Resolving module name for path => path
1>         Resolving module name for fs => fs
1>         Executing "after_prepare"  hook for all plugins.
1>         Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
1>         Executing "before_plugin_add"  hook for all plugins.
1>         Calling plugman.fetch on plugin "cordova-plugin-whitelist@1"
1>         Fetching plugin "cordova-plugin-whitelist@1" via npm
1>         Copying plugin "C:\Users\Sergei\AppData\Roaming\npm-cache\cordova-plugin-whitelist\1.2.1\package" => "c:\temp\BlankCordovaApp2\plugins\cordova-plugin-whitelist"
1>         Calling plugman.install on plugin "c:\temp\BlankCordovaApp2\plugins\cordova-plugin-whitelist" for platform "windows
1>         Installing "cordova-plugin-whitelist" for windows
1>         Running command: cmd "/s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\version.bat""
1>         Command finished with error code 0: cmd /s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\version.bat"
1>         Executing "before_plugin_install"  hook for "cordova-plugin-whitelist" on windows.
1>         Install start for "cordova-plugin-whitelist" on windows.
1>         Beginning processing of action stack for windows project...
1>         Action stack processing complete.
1>         Install complete for cordova-plugin-whitelist on windows.
1>         Executing "after_plugin_install"  hook for "cordova-plugin-whitelist" on windows.
1>         Searching PlatformJson files for differences between project vs. platform installed plugins
1>         No differences found between project and windows platform. Continuing...
1>         Generating config.xml from defaults for platform "windows"
1>         Executing "pre_package"  hook for all plugins.
1>         Resolving module name for shelljs => shelljs
1>         Resolving module name for path => path
1>         Resolving module name for fs => fs
1>         Executing "after_plugin_add"  hook for all plugins.
1>         Installing plugin "cordova-plugin-ms-adal" following successful platform add of windows
1>         Found variables for "cordova-plugin-ms-adal". Processing as cli_variables.
1>         Installing "cordova-plugin-ms-adal" for windows
1>         Running command: cmd "/s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\version.bat""
1>         Command finished with error code 0: cmd /s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\version.bat"
1>         Executing "before_plugin_install"  hook for "cordova-plugin-ms-adal" on windows.
1>         Install start for "cordova-plugin-ms-adal" on windows.
1>         Beginning processing of action stack for windows project...
1>         Action stack processing complete.
1>         Install complete for cordova-plugin-ms-adal on windows.
1>         Executing "after_plugin_install"  hook for "cordova-plugin-ms-adal" on windows.
1>         Resolving module name for shelljs => shelljs
1>         Resolving module name for path => path
1>         Patching windows universal app .projitems file: c:/temp/BlankCordovaApp2/platforms/windows/CordovaApp.projitems
1>         Resolving module name for shelljs => shelljs
1>         Resolving module name for path => path
1>         Resolving module name for fs => fs
1>         saving windows@4.1.0 into platforms.json
1>         Executing "after_platform_add"  hook for all plugins.
1>         ------ Updating plugins
1>         ------ Currently installed plugins: cordova-plugin-whitelist@1.2.1,cordova-plugin-ms-adal@0.6.2
1>         ------ Currently installed dependent plugins:
1>         ------ Currently configured plugins:
1>         ------ Building platform: windows
1>         Debug
1>         ------ Build configuration options: --debug
1>         Executing "before_compile"  hook for all plugins.
1>         Running command: cmd "/s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\build.bat --debug --buildConfig=c:\temp\BlankCordovaApp2\build.json --archs=arm --phone""
1>         Reading build config file: c:\temp\BlankCordovaApp2\build.json
1>         MSBuildToolsPath: C:\Program Files (x86)\MSBuild\14.0\bin\
1>         Building project: c:\temp\BlankCordovaApp2\platforms\windows\CordovaApp.Phone.jsproj
1>         	Configuration : debug
1>         	Platform      : arm
1>           CordovaApp.Phone -> c:\temp\BlankCordovaApp2\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug_Test\CordovaApp.Phone_1.0.0.0_arm_debug.appx
1>           CordovaApp.Phone -> c:\temp\BlankCordovaApp2\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug.appxupload
1>           Your package has been successfully created.
1>          BUILD OUTPUT: c:\temp\BlankCordovaApp2\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug_Test\CordovaApp.Phone_1.0.0.0_arm_debug.appx
1>         Command finished with error code 0: cmd /s /c "c:\temp\BlankCordovaApp2\platforms\windows\cordova\build.bat --debug --buildConfig=c:\temp\BlankCordovaApp2\build.json --archs=arm --phone"
1>         Executing "after_build"  hook for all plugins.
1>         Executing "after_compile"  hook for all plugins.
1>         ------ Copying back to project: Windows Phone (Universal)
1>         ------ Copied platforms\windows\build\phone\Debug\ARM\AppxManifest.xml to c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug\AppxManifest.xml
1>         ------ Copied platforms\windows\build\phone\Debug\ARM\CordovaApp.Phone.build.appxrecipe to c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug\CordovaApp.Phone.build.appxrecipe
1>         ------ Copied platforms\windows\build\phone\Debug\ARM\Microsoft.IdentityModel.Clients.ActiveDirectory.winmd to c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory.winmd
1>         ------ Copied platforms\windows\build\phone\Debug\ARM\Microsoft.IdentityModel.Clients.ActiveDirectory.xml to c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory.xml
1>         ------ Copied platforms\windows\build\phone\Debug\ARM\resources.pri to c:\temp\BlankCordovaApp2\bin\Windows Phone (Universal)\Debug\resources.pri
1>         ------ Copying generated _pkginfo.txt file
1>         ------ Done copying compiled files: Windows Phone (Universal)
1>         ------ Copying appx packages to output location
1>         ------ No packageOutputPath is specified for the project. Nothing to copy.
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:43.34
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

```
c:\temp\adalTest
λ cordova plugins
cordova-plugin-ms-adal 0.6.2 "ADAL for Cordova"
cordova-plugin-ms-adal-tests 0.0.1 "ADAL tests suite"
cordova-plugin-test-framework 1.1.1 "Test Framework"
cordova-plugin-whitelist 1.2.1 "Whitelist"

c:\temp\adalTest
λ cordova build windows --archs=arm -- --phone
"pre_package" hook is deprecated and will be removed in next Windows platform versions. Please use "after_prepare" if you want to manipulate files in www before app will be packaged.
Building project: c:\temp\adalTest\platforms\windows\CordovaApp.Phone.jsproj
        Configuration : debug
        Platform      : arm
  CordovaApp.Phone -> c:\temp\adalTest\platforms\windows\AppPackages\CordovaApp.Phon
  e_0.0.1.0_arm_debug_Test\CordovaApp.Phone_0.0.1.0_arm_debug.appx
  CordovaApp.Phone -> c:\temp\adalTest\platforms\windows\AppPackages\CordovaApp.Phon
  e_0.0.1.0_arm_debug.appxupload
  Your package has been successfully created.
```

**Comment by sgrebnov** [comment] 2016-02-25 11:31
Also, looks like 0.6.2 version is not on npm yet. Are you using Git url?

**Comment by SPDoctor** [comment] 2016-02-25 13:22
Yes, I got version 0.6.2 from Git URL. Current npm is 0.6.0 although I think it may actually be 0.6.1. I will try another rebuild as you suggest. I find it is often necessary to clean out the bin and platform directories completely as sometimes things get left behind.

**Comment by SPDoctor** [comment] 2016-02-25 13:33
@sgrebnov same result. Here's my build output:

`
1>------ Build started: Project: BlankCordovaApp6, Configuration: Debug Windows Phone (Universal) ------
1>  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.34
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.0.0 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bld\Windows Phone (Universal)\Debug
1>  ------    platformConfigurationBinDir: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug
1>  ------    buildCommand: build
1>  ------    platform: Windows Phone (Universal)
1>  ------    cordovaPlatform: windows
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: BlankCordovaApp6
1>  ------    projectSourceDir: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6
1>  ------    npmInstallDir: C:\Users\BillAyers\AppData\Roaming\npm
1>  ------    buildTarget: AppHostLocalDebugger
1>  ------    language: en-US
1>  ------ Adding platform: windows
1>  Executing "before_platform_add"  hook for all plugins.
1>  No version supplied. Retrieving version from config.xml...
1>  Adding windows project...
1>  PlatformApi successfully found for platform windows
1>  Creating Cordova Windows Project:
1>  	App Name  : BlankCordovaApp6
1>  	Namespace : io.cordova.myapp6a8090
1>  	Path      : C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows
1>  Copying template to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows
1>  Copying cordova-js sources to platform_www
1>  Copying node_modules to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows
1>  Updating manifest files with project configuration.
1>  Executing "before_prepare"  hook for all plugins.
1>  Executing "before_build"  hook for all plugins.
1>  Searching PlatformJson files for differences between project vs. platform installed plugins
1>  No differences found between project and windows platform. Continuing...
1>  Found "merges" for windows platform. Copying over existing "www" files.
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square150x150Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square150x150Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square150x150Logo.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square150x150Logo.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square30x30Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square30x30Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square310x310Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square310x310Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square44x44Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square44x44Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square44x44Logo.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square44x44Logo.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square70x70Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square70x70Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square71x71Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square71x71Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Square71x71Logo.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Square71x71Logo.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\StoreLogo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\StoreLogo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\StoreLogo.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\StoreLogo.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Wide310x150Logo.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Wide310x150Logo.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\icons\windows\Wide310x150Logo.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\Wide310x150Logo.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\screens\windows\SplashScreen.scale-100.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\SplashScreen.scale-100.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\screens\windows\SplashScreen.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\SplashScreenPhone.scale-240.png
1>  Copying image from C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\res\screens\windows\SplashScreenPhone.scale-240.png to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\images\SplashScreenPhone.scale-240.png
1>  Updated project successfully
1>  Executing "pre_package"  hook for all plugins.
1>  "pre_package" hook is deprecated and will be removed in next Windows platform versions. Please use "after_prepare" if you want to manipulate files in www before app will be packaged.
1>  Resolving module name for shelljs => shelljs
1>  Resolving module name for path => path
1>  Resolving module name for fs => fs
1>  Executing "after_prepare"  hook for all plugins.
1>  Installing plugin "cordova-plugin-ms-adal" following successful platform add of windows
1>  Found variables for "cordova-plugin-ms-adal". Processing as cli_variables.
1>  Installing "cordova-plugin-ms-adal" for windows
1>  Running command: cmd "/s /c ""C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\cordova\version.bat"""
1>  Command finished with error code 0: cmd /s /c ""C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\cordova\version.bat""
1>  Executing "before_plugin_install"  hook for "cordova-plugin-ms-adal" on windows.
1>  Install start for "cordova-plugin-ms-adal" on windows.
1>  Install complete for cordova-plugin-ms-adal on windows.
1>  Executing "after_plugin_install"  hook for "cordova-plugin-ms-adal" on windows.
1>  Resolving module name for shelljs => shelljs
1>  Resolving module name for path => path
1>  Patching windows universal app .projitems file: C:/Users/BillAyers/Documents/Visual Studio 2015/Projects/BlankCordovaApp6/BlankCordovaApp6/platforms/windows/CordovaApp.projitems
1>  Resolving module name for shelljs => shelljs
1>  Resolving module name for path => path
1>  Resolving module name for fs => fs
1>  Installing plugin "cordova-plugin-whitelist" following successful platform add of windows
1>  Found variables for "cordova-plugin-whitelist". Processing as cli_variables.
1>  Installing "cordova-plugin-whitelist" for windows
1>  Running command: cmd "/s /c ""C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\cordova\version.bat"""
1>  Command finished with error code 0: cmd /s /c ""C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\cordova\version.bat""
1>  Executing "before_plugin_install"  hook for "cordova-plugin-whitelist" on windows.
1>  Install start for "cordova-plugin-whitelist" on windows.
1>  Install complete for cordova-plugin-whitelist on windows.
1>  Executing "after_plugin_install"  hook for "cordova-plugin-whitelist" on windows.
1>  saving windows@4.3.1 into platforms.json
1>  Executing "after_platform_add"  hook for all plugins.
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-ms-adal@0.6.2,cordova-plugin-whitelist@1.2.1
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins:
1>  ------ Building platform: windows
1>  Debug
1>  ------ Build configuration options: --debug
1>  Executing "before_compile"  hook for all plugins.
1>  Reading build config file: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\build.json
1>  Searching for available MSBuild versions...
1>  Found MSBuild v14.0 at C:\Program Files (x86)\MSBuild\14.0\bin\
1>  Found MSBuild v12.0 at C:\Program Files (x86)\MSBuild\12.0\bin\
1>  Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework\v4.0.30319\
1>  Building project: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\CordovaApp.Phone.jsproj
1>  	Configuration : debug
1>  	Platform      : arm
1>    CordovaApp.Phone -> C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug_Test\CordovaApp.Phone_1.0.0.0_arm_debug.appx
1>    CordovaApp.Phone -> C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug.appxupload
1>    Your package has been successfully created.
1>   BUILD OUTPUT: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\AppPackages\CordovaApp.Phone_1.0.0.0_arm_debug_Test\CordovaApp.Phone_1.0.0.0_arm_debug.appx
1>  Executing "after_compile"  hook for all plugins.
1>  Executing "after_build"  hook for all plugins.
1>  ------ Copying back to project: Windows Phone (Universal)
1>  ------ Creating directory: C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug
1>  ------ Copied platforms\windows\build\phone\Debug\ARM\AppxManifest.xml to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug\AppxManifest.xml
1>  ------ Copied platforms\windows\build\phone\Debug\ARM\CordovaApp.Phone.build.appxrecipe to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug\CordovaApp.Phone.build.appxrecipe
1>  ------ Copied platforms\windows\build\phone\Debug\ARM\Microsoft.IdentityModel.Clients.ActiveDirectory.winmd to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory.winmd
1>  ------ Copied platforms\windows\build\phone\Debug\ARM\Microsoft.IdentityModel.Clients.ActiveDirectory.xml to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory.xml
1>  ------ Copied platforms\windows\build\phone\Debug\ARM\resources.pri to C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\bin\Windows Phone (Universal)\Debug\resources.pri
1>  ------ Copying generated _pkginfo.txt file
1>  ------ Done copying compiled files: Windows Phone (Universal)
1>  ------ Copying appx packages to output location
1>  ------ No packageOutputPath is specified for the project. Nothing to copy.
2>------ Deploy started: Project: BlankCordovaApp6, Configuration: Debug Windows Phone (Universal) ------
2>Error : DEP6810 : MdilXapCompile.exe failed with error code 2001. See log file 'C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\build\phone\bld\MDIL\MDILXapCompileLog.txt' for more details.
2>
2>Deployment failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

`

**Comment by SPDoctor** [comment] 2016-02-25 13:39
@sgrebnov Another thing to note is that it is the **deploy** step that fails, the build succeeds.

**Comment by sgrebnov** [comment] 2016-02-25 14:21
Could you post log file context here (or as gist) please
'C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\build\phone\bld\MDIL\MDILXapCompileLog.txt'

**Comment by SPDoctor** [comment] 2016-02-25 14:25
[MDILXapCompileLog.txt](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/files/146653/MDILXapCompileLog.txt)

**Comment by sgrebnov** [comment] 2016-02-25 14:42
Can't repro, assume you see this in newly created Cordova app with ADAL added as well, pls confirm.

Related error in log file
```
CrossGen failed
Error processing assembly C:\Users\BillAyers\Documents\Visual Studio 2015\Projects\BlankCordovaApp6\BlankCordovaApp6\platforms\windows\build\phone\bld\MSIL\Microsoft.IdentityModel.Clients.ActiveDirectory.winmd
Raw error code: 2148733978

```

**Comment by SPDoctor** [comment] 2016-02-25 15:40
Yes, I have removed and added ADAL a few times. I can create a project and it deploys fine until I add the v0.6.2 plugin. Remove plugin (leaving behind whitelist) and it deploys again.

Odd thing is the platform project deploys if you open its solution file. I'm on VS 2015 update 1 with Cordova Tools update 5.

**Comment by SPDoctor** [comment] 2016-02-25 16:04
Further tests: it deploys successfully to the Win Phone 8.1 emulator, only fails when you deploy to actual Win Phone 8.1 device.

**Comment by SPDoctor** [comment] 2016-02-25 20:40
@sgrebnov Test solution is at https://github.com/SPDoctor/MicrosoftGraphCordova if that helps.

**Comment by sgrebnov** [comment] 2016-02-29 08:10
I'll take a look, thank you!

**Comment by sgrebnov** [comment] 2016-03-03 09:40
I've reproduced this issue on another machine, working on fix...
```
Error: Deployment optimization failed due to an assembly that's not valid. Try rebuilding the project, and then try again. You may have previously installed the app with an earlier version of cordova-windows. Ensure the app is uninstalled from the phone and then try to run again.
You may not have the required environment or OS to run this project
```

**Comment by SPDoctor** [comment] 2016-03-03 14:05
That error message looks as though it might be a different issue...

**Comment by sgrebnov** [comment] 2016-03-07 08:52
Yeah, the message is different, but I see this only when using new plugin version (w/ re-compiled ADAL lib). Tried re-building ADAL SDK in different configurations (debug/release, sign options), didn't help. It could be a problem w/ my dev tools, going to try re-building the lib on another machine and using different msbuild version - msbuild12) PS - I'm currently OOF, until Wed.

**Comment by sgrebnov** [comment] 2016-03-07 08:57
Another difference is that it seems to work fine in `anycpu` for you, but in my case it does NOT work in both `anycpu` and `arm`

> If I drill down to the generated VS solution under platforms/windows and deploy to the device from that solution (targeting Any CPU) it deploys and works correctly on the device.

**Comment by SPDoctor** [comment] 2016-03-07 09:05
Thanks for continuing to investigate. I was using the Windows Phone target and Windows version set to 8.1.

**Comment by sgrebnov** [comment] 2016-03-07 10:14
I see [here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/d0b940d2-1c4e-4f28-9130-b45067088aa1/wp81-arm-deploying-to-device-problem-dep6810-in-release-mode?forum=wpdevelop) our two errors for the same problem.

> I'm currently struggling with deploying application to device in Release mode. While deploying I get error: DEP6810 : MdilXapCompile.exe failed with error code 2001. In log file: 
> CrossGen failed
> Error processing assembly P:\myproject\ARM\Release\MSIL\project.winmd
> Raw error code: 214873424
> I've tried also to create App Package and deploy it through Windows Phone Application Deployment (8.1) tool but I get error : "Deployment optimization failed due to an assembly that's not valid. Try rebuilding the project, and then try again" - of course rebuilding is not fixing the problem.

**Comment by sgrebnov** [comment] 2016-03-07 10:18
Looks like I found the problem and was able to get it working on my machine, could you please verify it on your side as well? The patch has been temporary submitted to `fix-wp81-deploy` branch.

To install it you can specify the following link when installing from Visual Studio
```
 https://github.com/AzureAD/azure-activedirectory-library-for-cordova#fix-wp81-deploy
```

**Comment by SPDoctor** [comment] 2016-03-07 10:45
Working :-D

**Comment by sgrebnov** [comment] 2016-03-07 10:47
Awesome, thanks a lot for verification!

**Comment by SPDoctor** [comment] 2016-03-07 10:47
Just one thing: Plugins -> Custom -> Git didn't work for me with that link: I had to download the plugin and use Plugins -> Custom -> Local and find the plugin directory.

**Comment by SPDoctor** [comment] 2016-03-07 10:48
Great job! Out of interest, what was the problem? I see you changed an XML file.

**Comment by SPDoctor** [comment] 2016-03-07 10:51
Ignore comment about the link - I think a double pasted the URL. Ooops.

**Comment by sgrebnov** [comment] 2016-03-07 10:57
There was an issue with assembly _Delay Signin_. I've also verified that produced app/assembly is valid for store submission in arm and anycpu using _Windows App Cert Kit_

**Comment by sgrebnov** [comment] 2016-03-07 10:58
Fixed in https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/d36fe7a42f6107446bfa439a4d71184990bb15c5

**Closed by sgrebnov** 2016-03-07 10:58 UTC
Labels: bug, triaged
