### ISSUE TITLE
'is not a valid Win32 application' error when using plugin on Windows/Windows Mobile 10.

### ISSUE THREAD

**Issue by MaartenX** [AzureAD/azure-activedirectory-library-for-cordova#77] opened 2016-06-13 06:31 UTC
I am trying to get my Cordova app to use AAD, but I cannot get it to work for the Windows/Windows Mobile targets.
When I call the plugin, it will try to call a native method, and I get the error: 'is not a valid Win32 application'. On my phone the error message is: 'The system cannot find the file specified'. This happens with my own app, but also when I run the sample from the 'sample' folder.

Repro details:

1. I am using Cordova 6.1.1 and I tried both 0.7.1 and 0.7.2-dev versions of the plugin. 
2. The errors occur when targeting the platforms Windows 10 and Windows Phone (Universal). Android works fine.
3. I tested this on my laptop with Windows Insider Preview Build 14361 (and the previous build), my Phone with Windows Insiders Build 14256 and Emulators running both builds 10240 and 10586.
4. The issue occurs when using Cordova from the command line and also when I use Visual Studio Cordova Tools (version 14.0.60527.5, running in Visual Studio Enterprise 2015 14.0.25123.00 2015 Update 2).

I have not enabled the SSO option.

I have attached the output of the sample application, after clicking the 'Create authentication context' button.
<img width="901" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6410630/15998765/3162ed9c-3141-11e6-86b1-ffb7c2ae3ca7.png">

**Comment by sgrebnov** [comment] 2016-06-22 11:08
I've just tried to reproduce the problem following instructions above and don't see this issue; @MaartenX, could you please share generated project (upload project created using instructions below on some online storage) so that I can take a look what could be the reason.
```
cordova create adalTest && cd adalTest
cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova/
xcopy plugins\cordova-plugin-ms-adal\sample\* www /Y /E
cordova platform add windows
cordova run windows --archs=x64 -- --appx=uap
```
![image](https://cloud.githubusercontent.com/assets/981580/16264470/844c0884-3882-11e6-94e6-78c747e20440.png)


PS. Same questions is posted here: http://stackoverflow.com/questions/37920820/is-not-a-valid-win32-application-error-when-using-cordova-adal-plugin-on-windo

**Comment by sgrebnov** [comment] 2016-06-22 12:51
Also tested on Windows 10 Mobile Emulator and it seems to work.

![image](https://cloud.githubusercontent.com/assets/981580/16267204/29144076-3891-11e6-81bb-5cd823466c96.png)

**Comment by sgrebnov** [comment] 2016-07-04 15:55
Closing as no-repro, please re-open with additional details if this issue is still actual.

**Closed by sgrebnov** 2016-07-04 15:55 UTC
Labels: bug, no-repro, pri:high, triaged, wfc, windows
