### ISSUE TITLE
Cache does not empty on ADFS 3.0

### ISSUE THREAD

**Issue by GaryMcAllister** [AzureAD/azure-activedirectory-library-for-cordova#68] opened 2016-05-09 13:06 UTC
Issue is as follows;

1.0, Login using a cordova app and an oAuth configured ADFS 3.0 server.
2.0, User-info is always null in ADFS so username parameter is irrelevant (added if condition to remove in my implementation).
3.0, Call clear cache to quit login.
4.0, Call the acquireToken (non-silent) again and the application auto-logs in (does not request credentials, is the fedAuth cookie cached in the browser?

Thanks

Gary

**Comment by sgrebnov** [comment] 2016-05-12 11:25
Sounds like a bug, acquireToken should ALWAYS prompt for credentials, I'll take a look (should also take a look on the native lib implementation to answer the latest question).

**Comment by sgrebnov** [comment] 2016-05-12 11:28
Is it Windows universal app? what version?

**Comment by sgrebnov** [comment] 2016-07-18 10:40
Unable to reproduce, is this issue still actual?

**Comment by GaryMcAllister** [comment] 2016-07-18 10:46
Will test later and let you know.

Assume you've logged out and tested login process?

**Comment by sgrebnov** [comment] 2016-09-01 14:42
Closing, please re-open if this issue is still actual.

**Closed by sgrebnov** 2016-09-01 14:42 UTC
Labels: bug, triaged, wfc
