### ISSUE TITLE
When using Broker component, calling acquireTokenSilentAsync will fail

### ISSUE THREAD

**Issue by jkotamaki** [AzureAD/azure-activedirectory-library-for-cordova#117] opened 2017-01-04 09:14 UTC
When using Intune + Authenticator App + Microsoft.ADAL.AuthenticationSettings.setUseBroker(true) works fine for the first acquireTokenAsync call. However, in case we call acquireTokenSilentAsync next, it will fail because there's no items in the tokenCache. 

Exact error:
Error: Prompt is not allowed and failed to get token:
    at fail (CordovaBridge.js:36)
    at Object.callbackFromNative (cordova.js:295)
    at processMessage (cordova.js:1081)
    at processMessages (cordova.js:1104)
    at pollOnce (cordova.js:973)
    at pollOnceFromOnlineEvent (cordova.js:960)

is there a way to make sure that tokenCache is updated after Authenticator App launches and user selects the account to be used in the app?

### Repro Environment Details
1. Installed plugin version:  Latest
2. Target Platform: `Android` 
3. Test device and OS version: `Samsung S7 Android 6.0`
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? Ionic Cordova 6.4.0, Visual Studio Code

**Comment by khalidaw** [comment] 2017-01-09 17:29
+1
Same issue (even without intune)

**Comment by matrosov-nikita** [comment] 2017-01-11 16:15
@jkotamaki, @khalidaw, to better understand your case, could you pls provide more information about how are you calling `acquireTokenSilent` method. What parameters do you pass? If you are passing `userId` parameter, what does it look like: GUID or user's email?

**Comment by jkotamaki** [comment] 2017-01-12 08:38
hi,

I've managed to solve the issue by doing following:

1. set Microsoft.ADAL.AuthenticationSettings.setUseBroker(true);
2. call context.acquireTokenAsync("https://graph.microsoft.com", clientId, redirectUri)
                .then(function (auth) { ....
, where RedirectUrl is formed like msauth://<my app's package name>/<app's Signature> (to get the signature, there's powershell available, which isn't working perfectly though :-D, but catching detailed error in cordova while calling acquireTokenAsync will provide the correct signature :-) )
3. Store userid to memory variable userId = auth.userInfo.userId; 
4. When calling acquireTokenSilentAsync, pass the userid as a parameter to a function:   context.acquireTokenSilentAsync("https://sometenant.sharepoint.com/...", clientId, userId)
                                .then(function (auth) {

Hopefully this will help also to someone, who is struggling with the same issue :-)

BR
Jukka

**Comment by khalidaw** [comment] 2017-01-12 11:14
What about reading cache returns empty values?

**Comment by jkotamaki** [comment] 2017-01-12 11:22
that is correct, cache is empty.

**Comment by matrosov-nikita** [comment] 2017-01-12 12:19
It's expected behavior because in this case cache entries are managed by broker internal cache, so adal cache is empty.

**Comment by khalidaw** [comment] 2017-01-12 13:23
This behaviour seems like Android only.
In iOS the ADAL library loads the items into its cache.
I wish have a way from ADAL it self, to know if user signed in, and which user [As it works without broker]

**Comment by vladimir-kotikov** [comment] 2017-01-20 15:19
@khalidaw, I'll close this one, because the original issue seems to have been fixed by #118. As for exposing broker's cache to the user, unfortunately this is currently impossible using 1.1.18, as ADAL doesn't expose methods for accessing broker's cache (see https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/v1.1.18/src/src/com/microsoft/aad/adal/AuthenticationContext.java#L215-L256)

However this does seem to be working in 1.10.0, so we'll need to get #112 merged first

**Closed by vladimir-kotikov** 2017-01-20 15:19 UTC
Labels: android, bug, triaged
