### ISSUE TITLE
acquireTokenSilentAsync fails to return a token after a successful login

### ISSUE THREAD

**Issue by candril** [AzureAD/azure-activedirectory-library-for-cordova#35] opened 2016-02-10 13:14 UTC
We've created a sample application following [Integrate Azure AD with an Apache Cordova app](https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-cordova/) and replaced the AAD app configuratin with our own.

We are able to get a working token by calling `context.acquireTokenAsync` and no errors are thrown. After a successful login we expect that `context.acquireTokenSilentAsync` should return a token without showing an UI. However, this method throws the following error 

> Error: The user credentials are need to obtain access token. Please call the non-silent acquireTokenWithResource methods

We also observed, that `context.tokenCache.readItems()` always returns an empty array, even if the user has logged in before.

We've tested this on iOS.

**Comment by sgrebnov** [comment] 2016-02-11 14:18
Confirm this issue, `ADALiOS.entitlements` file is not added to `Code Signing Entitlements` setting during plugin install so `$(AppIdentifierPrefix)com.microsoft.adalcache`  is not in keychain sharing group so token cache could not be updated. Manually adding this setting fixes this issue so manual and auto-tests pass. Looks like regression due to recent cordova or cordova-ios changes, investigating..

```
sg@sgs-MacBook-Pro.local:/Users/sg/Desktop/DirSearchClient  $ cordova --version
6.0.0
sg@sgs-MacBook-Pro.local:/Users/sg/Desktop/DirSearchClient  $ cordova platforms
Installed platforms: android 5.1.0, ios 4.0.1
```

**Comment by candril** [comment] 2016-02-11 14:19
After further investigations I've found that the CODE_SIGN_ENTITLEMENTS are not correctly set in the xcode project.

It seems that the project.pbxproj file is not updated from the hook script, but only if the plugin has been added before the platform:

**Hook script works:**

1. `cordova platform add ios`
2. `cordova plugin add cordova-plugin-ms-adal`

**Hook script fails:**

2. `cordova plugin add cordova-plugin-ms-adal`
1. `cordova platform add ios`

**Comment by candril** [comment] 2016-02-11 14:23
Another issue I found is that the hook script `configureEntitlementsIos.js` fails without an error on node version 5.6.0. It works fine on 0.12.7.

Installed versions:

```
$ cordova -v
6.0.0
$ cordova platforms
Installed platforms: ios 3.9.2
```

**Comment by sgrebnov** [comment] 2016-02-11 14:26
Thank you for reporting this - I'll take a look, created separate issue to make sure this is fixed https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/38

**Comment by sgrebnov** [comment] 2016-02-11 14:33
Looks like the following does not work anymore as we've recently switched to platform api for ios
```
var iosPlatform = ctx.requireCordovaModule('../plugman/platforms/ios');
...
if (iosPlatform && iosPlatform.purgeProjectFileCache) {
                console.log('Updating iOS projects cache...');
                iosPlatform.purgeProjectFileCache(platformRoot);
            }
```

**Comment by candril** [comment] 2016-02-11 14:34
Thanks!

Not sure if this is still related.
When building the project I now run into: 

> Code Sign error: The file “ADALiOS.entitlements” couldn’t be opened because there is no such file.

The file is in place `platforms/ios/<projectname>/Resources/ADALiOS.entitlements`.

I'll do further investigations.

**Comment by sgrebnov** [comment] 2016-02-11 14:59
I have a fix, will submit it after making it working on both pre- and post- platform api feature and additional tests

**Comment by sgrebnov** [comment] 2016-02-11 15:24
@candril I've pushed fix for this issue to repo master, pls let me know if it works for you..

**Comment by candril** [comment] 2016-02-11 16:10
The latest version works. Thanks @sgrebnov!

This error is not related and no longer reproduceable...
> Code Sign error: The file “ADALiOS.entitlements” couldn’t be opened because there is no such file

**Closed** 2016-02-11 16:55 UTC
Labels: bug, pri:high, triaged
