### ISSUE TITLE
acquireTokenAsync always prompting for sign-on

### ISSUE THREAD

**Issue by SPDoctor** [AzureAD/azure-activedirectory-library-for-cordova#50] opened 2016-03-12 13:56 UTC
In AuthenticationContext.js the comment states that the function 

```
...Acquires token using interactive flow if needed. It checks the cache to return existing result
if not expired. It tries to use refresh token if available. If it fails to get token with
refresh token, it will remove this refresh token from cache and start authentication.
```

When I test this it always requests authentication. If I follow the code path on, say, Windows 8.1 I notice it sets Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior.always in ADALProxy.js. Also in e.g. CordovaAdalPlugin.java, it sets PromptBehavior SHOW_PROMPT_ALWAYS = PromptBehavior.Always. I suggest that in both cases the prompt behaviour should be set to **auto**. If I modify ADALProxy.js and set PromptBehavior.auto it seems to work as expected.

There is an option to set
` <preference name="adal-use-corporate-network" value="true" /> 
`in the plug-in config that should change the behaviour, but that is not the default (and I think applies to the intranet scenario only). I assume the intention was that the library takes care of cached credentials and refresh tokens without the caller having to explicitly check the cache, If not, we should change the documentation of the method to make this clear.

**Comment by SPDoctor** [comment] 2016-03-14 13:25
Please see pull request `Changed PromptBehavior from "always" to "auto" #51`. I think this fixes the issue for Windows platform implementation.

**Comment by SPDoctor** [comment] 2016-03-14 15:46
Sergei, please could you look at my suggested code which I have added to the previous pull request. This moves the acquireTokenSilentAsync call inside the plugin and only for the Windows Phone path as this explicit call is only needed for Windows Phone. I think this will also make it possible for the acquireTokenAsync method to be consistent with the documentation, if we want to go that route.

**Comment by sgrebnov** [comment] 2016-03-15 09:14
@SPDoctor thank you for the pull request, but `PromptBehaviour,Always` is used by design here (I'll also review comments so ensure they are correct). All of native ADAL libraries are moving toward a design in which AcquireToken is always showing a UX and AcquireTokenSilent never does so.

Adding @vibronet for further clarification here..

PS. Is there any technical reason/problem other then writing extra code to call AcquireTokenSilent first and then AcquireToken as demonstrated in [this tutorial](https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-cordova/)?

**Comment by SPDoctor** [comment] 2016-03-15 09:47
Thanks Sergei. I think the important thing is to be consistent here. So making PromptBehaviour of acquireTokenAsync "always" by default is perfectly satisfactory as long as it is:

- The same with all versions of ADAL libraries.
- The documentation reflects this.
- The sample code always uses this pattern.
- The behaviour is the same regardless of underlying platform.

I see a big risk of confusion in what is already quite difficult for typical developers who have many demands on their time and are not able to dig deep into this topic, and a frustrating early experience can lead to discouragement when we want developers to move to this model. i have seen this in classes and workshops and I think there is evidence in the article feedback. I was particularly worried that if the developer didn't follow the exact pattern of nesting the two AcquireToken.. methods, (which based on the current documentation would appear to be unnecessary) then you would get different behaviour on different platforms.

I suggested code that embeds the Windows Phone continuation callback behaviour within the plugin to make the Windows Phone behaviour consistent with other platforms in the event that a developer calls AcquireTokenAsync without first calling the AcquireTokenSilentAsync. If we make AcquireTokenAsync always prompt then that problem goes away - good. 

But are you sure that you can get all implementations of ADAL to follow this? It seems like a breaking change as existing code will start auth. prompting on every call. My big worry is that if the behaviour of AcquireTokenAsync were to end up being inconsistent we have a terrible mess! I'll be interested to hear Vittorio's view.

**Comment by SPDoctor** [comment] 2016-03-15 09:50
Sorry, one other objection!

This pattern (AcquireTokenSilentAsync, call AcquireTokenAsync on error) could be regarded as a bad coding practice because you are using error handling as part of the normal logic flow.

**Comment by sgrebnov** [comment] 2016-05-31 10:15
Closing this topic as there is no clarification from @vibronet. I think we are good here as all statements below are true:

 - [x] The behavior is the same regardless of underlying platform.
 - [x] The documentation reflects this.
 - [x] The sample code always uses this pattern.

**Closed by sgrebnov** 2016-05-31 10:15 UTC
Labels: discussion, triaged
