### ISSUE TITLE
Cache is always empty on Windows Phone 8.1 update 2

### ISSUE THREAD

**Issue by GaryMcAllister** [AzureAD/azure-activedirectory-library-for-cordova#54] opened 2016-03-20 19:27 UTC
Cache is never populated on Windows Phone 8.2 following successful login.

After successful login the token cache is empty.

**Comment by GaryMcAllister** [comment] 2016-03-20 19:28
I have created a Windows universal app

**Comment by sgrebnov** [comment] 2016-03-21 14:56
What plugin version do you use? Are you testing on real device or emulator?

**Comment by GaryMcAllister** [comment] 2016-03-21 21:18
I am using 0.6.2 and a real windows phone

**Comment by GaryMcAllister** [comment] 2016-04-11 07:48
Any update on this ?...

**Comment by Klotair** [comment] 2016-04-11 14:42
Hi, It seems that I got the same error on an Android 4.2.2. My app works fine from android 4.3.1 to the last versions.

I'm using 
  "name": "cordova-plugin-ms-adal",
  "version": "0.6.2"

After the user have been logged, when my code reach that lines: 
The "items" array is empty, so the login is displayed again.
`
adalContext.tokenCache.readItems().then(function (
                    if (items.length > 0) {
                        adalContext = new Microsoft.ADAL.AuthenticationContext(items[0].authority);
                    }
...
`
What are the supported android versions ?
Thanks

**Comment by sgrebnov** [comment] 2016-04-12 09:33
@Klotair,
Looks like caching support for Android Api level 17 and below  (<= 4.2.x) requires some extra work:
https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/80

I'll clarify whether we support those targets.

PS. This answers why 4.3.1 (Api level 18) works

**Comment by sgrebnov** [comment] 2016-04-15 09:05
@Klotair I've created separate issue below to track this further (after internal discussion we decided to implement missing functionality for Android Api level 15..17 as it is still quite popular)
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/60

@GaryMcAllister I'll start working on this soon, will keep you updated in this thread

**Comment by sgrebnov** [comment] 2016-04-22 15:46
@GaryMcAllister Do you refer to Windows Phone 8.2 or Windows Phone 8.1 Update 2?

**Comment by sgrebnov** [comment] 2016-04-22 15:48
I've just made a quick test on Nokia Lumia 520 WP 8.1 and it seems to work correct. @GaryMcAllister What device do you use for testing?

**Comment by GaryMcAllister** [comment] 2016-04-22 19:29
Phone 8.1 update 2

**Comment by GaryMcAllister** [comment] 2016-04-22 19:30
Let me go through my own app testing again and I'll let you know.

Sorry I can't give you clarity immediately

**Comment by GaryMcAllister** [comment] 2016-04-25 18:50
Hi, Still not working for me.. Works on iPhone version of the same app.

My device is Lumia 640 LTE, Windows Phone 8.1 Update .

**Comment by GaryMcAllister** [comment] 2016-04-25 18:51
`manager.AuthContext.tokenCache.readItems().then(function (cacheItems) {
                    if (cacheItems.length > 0) {
                        testUserId = cacheItems[0].userInfo.userId;
                    }

                    manager.AuthContext.acquireTokenSilentAsync(org.ResourceUrl, org.AppId, testUserId).then(function (authResult) {

                        manager.log("acquired token silently exp: " + authResult.expiresOn);

                        if (callback) {
                            callback(authResult);
                        }

                    }, function (err) {
                        manager.error("Failed to acquire token silently: " + manager.pre(err));

                        if (failurecallback) {
                            failurecallback();
                        }
                    });
                }, function (err) {
                    manager.error("Unable to get User ID from token cache. Have you acquired token already? " + manager.pre(err));
                    self.acquireToken(org, callback, failurecallback);
                });`

**Comment by GaryMcAllister** [comment] 2016-04-25 19:35
Here is the error I am getting when debugging.

WinRTError: No such interface supported

System.InvalidCastException: Specified cast is not valid.
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Anonymous function (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/src/windows/ADALProxy.js:209:17)
   at _fulfilled (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/www/utility.js:263:29)
   at Deferred.prototype.then (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/www/utility.js:329:25)
   at ADALProxy.tokenCacheReadItems (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/src/windows/ADALProxy.js:208:13)
   at module.exports (ms-appx://18707digihealth.digihealth/www/cordova.js:901:13)
   at cordovaBridge.executeNativeMethod (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/www/CordovaBridge.js:41:9)
   at TokenCache.prototype.readItems (ms-appx://18707digihealth.digihealth/www/plugins/cordova-plugin-ms-adal/www/TokenCache.js:37:5)
   at self.createContextAndAcquireToken (ms-appx://18707digihealth.digihealth/www/scripts/app/AppViewModels/AzureAd.js:12:17)
   at self.refreshToken (ms-appx://18707digihealth.digihealth/www/scripts/app/AppViewModels/LoginViewModel.js:70:13)
   at tokenRefresh (ms-appx://18707digihealth.digihealth/www/scripts/app/Lists-Main.js:105:25)

**Comment by sgrebnov** [comment] 2016-04-27 09:13
I've tried to reproduce this issue using your code snippet and it worked for me (Lumia 520 8.1 Update 2).
Here are my ideas how we can triage this further:
* [To detect if this is app or tools version specific]. Does it repro on Visual Studio Windows Phone 8.1 emulator as well?
* [To detect if this is device/OS version specific]. Do you see this issue on other Windows Phone devices (if you have a chance to test), is it Update 2 specific?
* What target chip architecture do you use? Arm or AnyCpu?

**Comment by sgrebnov** [comment] 2016-04-27 09:21
This also looks to be identical to https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/30 which was fixed in 0.6.2

**Comment by sgrebnov** [comment] 2016-04-27 09:44
@GaryMcAllister, can you try the following steps to ensure you have plugin version w/ appropriate fix:

```
cordova plugin rm cordova-plugin-ms-adal
cordova platform rm windows
cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova
cordova platform add windows
```
PS. For VSCordovaTools: to remove windows platform you can simply remove <your-app>/platforms/windows folder (it will be restored automatically during build); if you have some older version you can remove /bld and /bin folders. This will guarantee clean build.

**Comment by GaryMcAllister** [comment] 2016-04-27 10:00
Will do, thanks.

Will try on an alternative device later this week.

**Comment by sgrebnov** [comment] 2016-05-19 10:05
This issue is inactive for a while, please re-open, if the problem is still actual.

**Closed by sgrebnov** 2016-05-19 10:05 UTC
Labels: bug, no-repro, triaged, wfc, windows
